######################
# TRDS configuration #
######################

# some of these are overridden by user settings in local.conf

# controls

left       4
right      8
thrust   256
triggera  64
triggerb 128
menu       2
beam     512

# network

channel 11
updatefrequency 6

# sound parameters

rate_idle            4000
rate_delta           300
rate_speed_factor    3000
rate_particle_ship   18000
rate_particle_sob    15000
period_tracking      40
volume_dead          100
volume_idle          30
volume_speed_factor  160
volume_particle_bg   60
volume_particle_sob  100
volume_particle_ship 127
volume_shot          120
volume_tracking      60

thrust_sound   sounds/thrust.raw
shootA_sound   sounds/shootA.raw
shootB_sound   sounds/shootB.raw
dead_sound     sounds/dead.raw
particle_sound sounds/particle.raw
tracking_sound sounds/tracking.raw

# music and sound settings

music      1
gamemusic  2
sound      1

# mod params

music_filename              cruising_in_space.mod
music_intro_pos             0
music_game_pos              87
music_game_over_pos         86
music_game_random_patterns  14
music_silent_pattern        101

# splash screen
splash splash/splash_Info.bin splash/splash_Tiles.bin splash/splash_Map.bin splash/splash_Pal.bin

mapship mapship_Sprite.bin

# color settings (html notation)

color_player 639C63  # green
color_player D81515  # red
color_player 1515D8  # blue
color_player EAFF00  # yellow

# only 4-player games are supported => only four colors needed
#color_player FF6C00  # orange
#color_player FF00FF  # pink
#color_player 00FF90  # cyan
#color_player 808080  # gray
