lives 5

ship_drag 0.08
ship_mass 1000

ship_rotspeed 8.15
ship_thrust 50
ship_strength 100
ship_gas 2000
ship_gas_usage_rate 1
roundsa 100
roundsb 4
ship_damage 100
ship_price                   20

autofire_rate                8
weapon_b_max_repetition_rate 50
bullet_speed                 2.2

# economics

base_income_rate             180
start_credits                100
gas_price                    0.0005

weapon_a_ammo_price          1
weapon_a_weapon_price        20
weapon_a_ammo_quantum        50

single_ammo_price            5
single_weapon_price          20
single_ammo_quantum          10

mine_ammo_price              5
mine_weapon_price            20
mine_ammo_quantum            10

buck_ammo_price              5
buck_weapon_price            20
buck_ammo_quantum            10

heat_ammo_price              5
heat_weapon_price            20
heat_ammo_quantum            10

mono_ammo_price              5
mono_weapon_price            50
mono_ammo_quantum            10

resource_node_income_rate    180
node_ammo_price              20
node_weapon_price            20
node_ammo_quantum            1

sentry_ammo_price            60
sentry_weapon_price          30
sentry_ammo_quantum          1

heatsentry_ammo_price        100
heatsentry_weapon_price      130
heatsentry_ammo_quantum      1

bomb_ammo_price              400
bomb_weapon_price            200
bomb_ammo_quantum            1

asm_ammo_price              40 
asm_weapon_price            200
asm_ammo_quantum            1

# sob params

sentry_damage                100
building_strength            700
sentry_gun_rate              60
platform_strength            8000
platform_repair_rate         0.10
sob_vicinity_range           48

# special weapons
bomb_damage                  10000
asm_damage                   400
asm_armtime                  5 

# upgrades

upgrade_ship_strength_price         50
upgrade_ship_strength_increment     1.5

upgrade_stealth_price               50

upgrade_radar_price                 50

upgrade_capacity_price              50
upgrade_gas_capacity_increment      1000
upgrade_weapona_capacity_increment  50
upgrade_weaponb_capacity_increment  2

upgrade_firing_rate_price           50
upgrade_firing_rate_factor          0.3

upgrade_building_strength_price     50
upgrade_building_strength_increment 1.5 

upgrade_node_gather_price           50
upgrade_node_gather_rate_factor     0.1                   
                                    
upgrade_repair_price                50
upgrade_repair_factor               0.2

upgrade_sentry_rate_price           50
upgrade_sentry_rate_factor          0.2

upgrade_damage_price                50
upgrade_damage_increment            1.5

upgrade_bullet_speed_price          50
upgrade_bullet_speed_increment      0.25

upgrade_thrust_price                50
upgrade_thrust_increment            10

upgrade_weight_price                50
upgrade_weight_factor               0.15

# additional allowed weapons

mono
sentrygun
heatsentrygun
bomb
asmissile
