# game
resurrect_time               200
end_time                     200
immortal_time                0
minplayers                   1
maxplayers                   1
include                      thrust.ship
star_spread_speed            1
empty_gas_die_time           600

# environment damage
background_damage            100
particle_damage              0

# physics
particle_drag                1000
particle_mass                1
weapon_a_mass                1
weapon_b_mass                0
gas_mass                     0
gravity                      0.015
liquid_drag                  0.93

# platform
gas_refill_rate              5
strength_refill_rate         1        
weapon_a_refill_rate         4
weapon_b_refill_rate         50
platform_friction            0.005

# generic weapon params
weapon_b_max_repetition_rate 1
bullet_speed                 4

# allowed weapons
mono

# specific weapon params
oneshot_damage               100      
buckshot_spread_speed        0.1
seek_radius                  200      
heatseeker_accel             0.1      
heatseeker_armtime           50       
heatseeker_lifetime          200      
mine_lifetime                1200     
singleshot_armtime           100       
buckshot_armtime             45       
spraystream_spread           0.3      

strut_length                 40       
beam_range                   50       
outer_space                  16       

doortime                     480
gunstation_rate              200
gunstation_reaction_distance 120
powerplant_inactive_time     600
fuel_sob_capacity            300

gunstation_damage            1

fuel_strength                80
gun_strength                 80
powerplant_strength          80

ball_score 0

gun_score          750
fuel_destroy_score 150
fuel_fill_score    300
#planet_score       2000 # not implemented
#new_ship           10000 # not implemented

required_balls 1
